# .github/funding.yml

github: "https://github.com/sponsors/allyelvis"  # URL to your GitHub Sponsors page
patreon: "https://www.patreon.com/allyelvis"    # Optional: URL to your Patreon page (if you have one)
open_collective: "https://opencollective.com/allyelvis"  # Optional: URL to your Open Collective page (if you have one)
ko_fi: "https://ko-fi.com/allyelvis"            # Optional: URL to your Ko-Fi 
