name: Generate ML MCP Servers Schema (PHP)

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  generate-ml-schema:
    name: Generate MCP Schema using PHP AI Analyzer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, json, intl, dom
          coverage: none

      - name: Install Dependencies
        run: |
          composer init --no-interaction || true
          composer require symfony/yaml guzzlehttp/guzzle php-ai/php-ml nesbot/carbon

      - name: Run ML Analyzer
        run: php .github/scripts/generate_ml_mcpservers.php

      - name: Commit and Push Generated Schema
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ml_mcp_schema.json
          git commit -m "🤖 Auto-generated ML MCP Servers Schema [PHP] [skip ci]" || echo "No changes to commit"
          git push
